export const homeObjOne = {
  lightBg: false,
  primary: true, 
  lightBg: false, 
  imgStart: "", 
  lightTopLine: true, 
  lightText: true, 
  lightTextDesc: true,
  topLine: "Marketing Agency",
  headline: "Lead Generation Specialist for online Business",
  description: "We help business owners increase their revenue. Our team can help you achieve your business goals.",
  buttonLabel: "Get Started",
  img: require('../../images/teach.svg'),
  alt: "Image",
  start: "",
}

export const homeObjTwo = {
  lightBg: true,
  primary: false, 
  imgStart: "", 
  lightTopLine: false, 
  lightText: false, 
  lightTextDesc: true,
  topLine: "Marketing Agency",
  headline: "Lead Generation Specialist for online Business",
  description: "We help business owners increase their revenue. Our team can help you achieve your business goals.",
  buttonLabel: "Get Started",
  img: require('../../images/pic.svg'),
  alt: "Image",
  start: true,
}

export const homeObjThree = {
  lightBg: false,
  primary: true, 
  lightBg: false, 
  imgStart: "", 
  lightTopLine: true, 
  lightText: true, 
  lightTextDesc: true,
  topLine: "Marketing Agency",
  headline: "Lead Generation Specialist for online Business",
  description: "We help business owners increase their revenue. Our team can help you achieve your business goals.",
  buttonLabel: "Get Started",
  img: require('../../images/prof.svg'),
  alt: "Image",
  start: "",
}

export const homeObjFour = {
  lightBg: false,
  primary: true, 
  lightBg: false, 
  imgStart: "start", 
  lightTopLine: true, 
  lightText: true, 
  lightTextDesc: true,
  topLine: "Marketing Agency",
  headline: "Lead Generation Specialist for online Business",
  description: "We help business owners increase their revenue. Our team can help you achieve your business goals.",
  buttonLabel: "Get Started",
  img: require('../../images/code.svg'),
  alt: "Image",
  start: "true",
}